.TH "ps_line_pt.c" 3 "Fri Nov 5 2021" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ps_line_pt.c \- Documented computation of Poisson shot noise and tree-level line power spectrum in real and redshift-space\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBPS_line\fP (struct \fBCosmology\fP *Cx, double k, double z, size_t line_id)"
.br
.RI "Compute the real-space 3D power spectrum of emission lines in unit of micro K^2 Mpc^3\&. "
.ti -1c
.RI "double \fBPS_line_RSD\fP (struct \fBCosmology\fP *Cx, struct \fBCosmology\fP *Cx_ref, double k, double mu, double z, size_t line_id)"
.br
.RI "Compute the redshift-space 3D power spectrum of emission lines in unit of micro K^2 Mpc^3 as a function of wavenumber and angle w\&.r\&.t\&. "
.ti -1c
.RI "int \fBps_line_multipoles_integrand\fP (unsigned ndim, const double *x, void *p, unsigned fdim, double *fvalue)"
.br
.RI "Compute the multipole moments of redshift-space power spectrum of emission lines in unit of micro K^2 Mpc^3, integrating over the angle w\&.r\&.t LOS, weighted by\&. "
.ti -1c
.RI "double \fBps_line_multipoles\fP (struct \fBCosmology\fP *Cx, struct \fBCosmology\fP *Cx_ref, double k, double z, size_t line_id, int ell)"
.br
.ti -1c
.RI "double \fBPS_shot\fP (struct \fBCosmology\fP *Cx, double z, size_t line_id)"
.br
.RI "Compute the Poisson shot noise in unit of micro K^2 Mpc^3\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBglobals\fP \fBgb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Documented computation of Poisson shot noise and tree-level line power spectrum in real and redshift-space\&. 

Azadeh Moradinezhad Dizgah, November 4th 2021
.PP
NOTE TODO: Add the 1loop redshift-space power spectrum of the line\&. This requires implementing FFTLog, still in progress For the moment we stick to the tree-level expression of line power spectrum in redshift-space\&.
.PP
In summary, the following functions can be called from other modules:
.IP "1." 4
\fBPS_line()\fP computes tree-level line power spectrum in real-space
.IP "2." 4
\fBPS_line_RSD()\fP computes the tree-level line power spectrum in redshift-space, as a function of wavenumber and angle w\&.r\&.t LOS
.IP "3." 4
ps_line_multipoles() computes the redshift-space multipoles of the line power spectrum
.IP "4." 4
\fBPS_shot()\fP computes the poisson shot noise 
.PP

.SH "Function Documentation"
.PP 
.SS "double PS_line (struct \fBCosmology\fP * Cx, double k, double z, size_t line_id)"

.PP
Compute the real-space 3D power spectrum of emission lines in unit of micro K^2 Mpc^3\&. 
.PP
\fBParameters\fP
.RS 4
\fICx\fP Input: \fBCosmology\fP structure 
.br
\fIk\fP Input: wavenumber in unit of 1/Mpc\&. 
.br
\fIz\fP Input: redshift 
.br
\fIline_id\fP Inpute: id of the line to be considered\&. 
.RE
.PP
\fBReturns\fP
.RS 4
tree-level P_clust(k) 
.br
 
.RE
.PP

.SS "int ps_line_multipoles_integrand (unsigned ndim, const double * x, void * p, unsigned fdim, double * fvalue)"

.PP
Compute the multipole moments of redshift-space power spectrum of emission lines in unit of micro K^2 Mpc^3, integrating over the angle w\&.r\&.t LOS, weighted by\&. 
.PP
\fBParameters\fP
.RS 4
\fICx\fP Input: \fBCosmology\fP structure 
.br
\fICx_ref\fP Input: Reference cosmology structure, needed for AP effect 
.br
\fIk\fP Input: wavenumber in unit of 1/Mpc\&. 
.br
\fIz\fP Input: redshift 
.br
\fIline_id\fP Inpute: id of the line to be considered\&. 
.br
\fIell\fP Inpute: the multipole 
.RE
.PP
\fBReturns\fP
.RS 4
P_ell(k) 
.br
 
.RE
.PP

.SS "double PS_line_RSD (struct \fBCosmology\fP * Cx, struct \fBCosmology\fP * Cx_ref, double k, double mu, double z, size_t line_id)"

.PP
Compute the redshift-space 3D power spectrum of emission lines in unit of micro K^2 Mpc^3 as a function of wavenumber and angle w\&.r\&.t\&. LOS
.PP
\fBParameters\fP
.RS 4
\fICx\fP Input: \fBCosmology\fP structure 
.br
\fICx_ref\fP Input: Reference cosmology structure, needed for AP effect 
.br
\fIk\fP Input: wavenumber in unit of 1/Mpc\&. 
.br
\fImu\fP Inpute: angle w\&.r\&.t LOS 
.br
\fIz\fP Input: redshift 
.br
\fIline_id\fP Inpute: id of the line to be considered\&. 
.RE
.PP
\fBReturns\fP
.RS 4
tree-level P_clust(k,mu) 
.br
 
.RE
.PP
to plot the power spectrum in units of micro K^2 Mpc^3
.SS "double PS_shot (struct \fBCosmology\fP * Cx, double z, size_t line_id)"

.PP
Compute the Poisson shot noise in unit of micro K^2 Mpc^3\&. 
.PP
\fBParameters\fP
.RS 4
\fICx\fP Input: \fBCosmology\fP structure 
.br
\fIz\fP Input: redshift 
.br
\fIline_id\fP Inpute: id of the line to be considered\&. 
.RE
.PP
\fBReturns\fP
.RS 4
P_poisson 
.br
 in unit of micro K^2 Mpc^3 
.RE
.PP
Boltzmann constant in unit of erg K^-1
.PP
in unit of erg/s
.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
