.TH "Source Directory Reference" 3 "Sat Nov 13 2021" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcosmology\&.c\fP"
.br
.RI "Documented cosmology module\&. "
.ti -1c
.RI "file \fBIR_res\&.c\fP"
.br
.RI "Documented IR_res module\&. "
.ti -1c
.RI "file \fBline_ingredients\&.c\fP"
.br
.RI "Documented line_ingredients module\&. "
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "Documented main module, including functions to initilize and cleanup the cosmology structure and examples of calls to functions in other modules to compute the line clustering and shot power spectrum\&. "
.ti -1c
.RI "file \fBps_halo_1loop\&.c\fP"
.br
.RI "Documented real-space, direct integration computation of 1loop contributions of the halo/galaxy power spectrum See arXiv:2010\&.14523 for explicit expressions\&. "
.ti -1c
.RI "file \fBps_line_hm\&.c\fP"
.br
.RI "Documented halo-model computation of line power spectrum, including clustering and stochastic contributions beyond Poisson limit\&. "
.ti -1c
.RI "file \fBps_line_pt\&.c\fP"
.br
.RI "Documented computation of Poisson shot noise and tree-level line power spectrum in real and redshift-space\&. "
.ti -1c
.RI "file \fBsurvey_specs\&.c\fP"
.br
.RI "Documented computation of some survey-related functions\&. "
.ti -1c
.RI "file \fButilities\&.c\fP"
.br
.RI "Documented basic utility functions used by other modules of the code\&. "
.ti -1c
.RI "file \fBwnw_split\&.c\fP"
.br
.RI "Documented wiggle-nowiggle split based on 3d Gaussian filter in linear k, and using the Eisentein-Hu wiggle-no wiggle template arXiv:astro-ph/9709112\&. "
.in -1c
