.TH "Class_Cosmology_Struct" 3 "Sun Nov 7 2021" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Class_Cosmology_Struct \- Structure to store cosmology structure from CLASS code\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Global_Structs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct precision \fBpr\fP"
.br
.ti -1c
.RI "struct background \fBba\fP"
.br
.ti -1c
.RI "struct thermo \fBth\fP"
.br
.ti -1c
.RI "struct perturbs \fBpt\fP"
.br
.ti -1c
.RI "struct transfers \fBtr\fP"
.br
.ti -1c
.RI "struct primordial \fBpm\fP"
.br
.ti -1c
.RI "struct spectra \fBsp\fP"
.br
.ti -1c
.RI "struct nonlinear \fBnl\fP"
.br
.ti -1c
.RI "struct lensing \fBle\fP"
.br
.ti -1c
.RI "struct output \fBop\fP"
.br
.ti -1c
.RI "ErrorMsg \fBerrmsg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to store cosmology structure from CLASS code\&. 
.SH "Field Documentation"
.PP 
.SS "struct background ba"

.SS "ErrorMsg errmsg"

.SS "struct lensing le"

.SS "struct nonlinear nl"

.SS "struct output op"

.SS "struct primordial pm"

.SS "struct precision pr"

.SS "struct perturbs pt"

.SS "struct spectra sp"

.SS "struct thermo th"

.SS "struct transfers tr"


.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
