.TH "globals" 3 "Sun Nov 7 2021" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
globals \- A global structure including the values of cosmological parmaeters, 2d interpolator of SFR, and names of various files\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Global_Structs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBH0\fP"
.br
.ti -1c
.RI "double \fBc\fP"
.br
.ti -1c
.RI "double \fBAs\fP"
.br
.ti -1c
.RI "double \fBlogAs\fP"
.br
.ti -1c
.RI "double \fBns\fP"
.br
.ti -1c
.RI "double \fBh\fP"
.br
.ti -1c
.RI "double \fBOmega_cdm\fP"
.br
.ti -1c
.RI "double \fBOmega_b\fP"
.br
.ti -1c
.RI "double \fBOmega_r\fP"
.br
.ti -1c
.RI "double \fBOmega_lambda\fP"
.br
.ti -1c
.RI "double \fBOmega_g\fP"
.br
.ti -1c
.RI "double \fBOmega_nu\fP"
.br
.ti -1c
.RI "double \fBb1\fP"
.br
.ti -1c
.RI "double \fBsigFOG0\fP"
.br
.ti -1c
.RI "long \fBNpars\fP"
.br
.ti -1c
.RI "double \fBz_i\fP"
.br
.ti -1c
.RI "double \fBrho\fP"
.br
.ti -1c
.RI "double \fBmass\fP"
.br
.ti -1c
.RI "double \fBkp\fP"
.br
.ti -1c
.RI "double \fBng\fP"
.br
.ti -1c
.RI "double \fBvolume\fP"
.br
.ti -1c
.RI "double \fBkf\fP"
.br
.ti -1c
.RI "double \fBh_m\fP"
.br
.ti -1c
.RI "double \fBM_min\fP"
.br
.ti -1c
.RI "double \fBM_max\fP"
.br
.ti -1c
.RI "double \fBz_max\fP"
.br
.ti -1c
.RI "char \fBproject_home\fP [FILENAME_MAX]"
.br
.ti -1c
.RI "char \fBoutput_dir\fP [FILENAME_MAX]"
.br
.ti -1c
.RI "char \fBdata_dir\fP [FILENAME_MAX]"
.br
.ti -1c
.RI "char \fBdata_priors\fP [FILENAME_MAX]"
.br
.ti -1c
.RI "double \fBPS_kmin\fP"
.br
.ti -1c
.RI "double \fBPS_kmax\fP"
.br
.ti -1c
.RI "char \fBSFR_filename\fP [FILENAME_MAX]"
.br
.ti -1c
.RI "char \fBPlanck_Fisher_filename\fP [FILENAME_MAX]"
.br
.ti -1c
.RI "gsl_interp_accel * \fBlogM_accel_ptr\fP"
.br
.ti -1c
.RI "gsl_interp_accel * \fBz_accel_ptr\fP"
.br
.ti -1c
.RI "gsl_spline2d * \fBlogSFR_spline2d_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A global structure including the values of cosmological parmaeters, 2d interpolator of SFR, and names of various files\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
