.TH "Global_Structs.h" 3 "Tue Nov 9 2021" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Global_Structs.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBClass_Cosmology_Struct\fP"
.br
.RI "Structure to store cosmology structure from CLASS code\&. "
.ti -1c
.RI "struct \fBCosmology\fP"
.br
.RI "Structure that holds varioud quantities that need to be evaluated for a given choice of cosmological paramteres\&. "
.ti -1c
.RI "struct \fBLine\fP"
.br
.RI "Structure that holds the Line-related quantities, including the interpolators for first and second moments of the line luminosity and the linear and quadratic luminosity-weighted line biases\&. "
.ti -1c
.RI "struct \fBglobals\fP"
.br
.RI "A global structure including the values of cosmological parmaeters, 2d interpolator of SFR, and names of various files\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
