.TH "header.h" 3 "Thu Jan 20 2022" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
header.h
.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <float\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <omp\&.h>\fP
.br
\fC#include <mpi\&.h>\fP
.br
\fC#include <gsl/gsl_errno\&.h>\fP
.br
\fC#include <gsl/gsl_spline\&.h>\fP
.br
\fC#include <gsl/gsl_interp2d\&.h>\fP
.br
\fC#include <gsl/gsl_spline2d\&.h>\fP
.br
\fC#include <gsl/gsl_sf_bessel\&.h>\fP
.br
\fC#include <gsl/gsl_sf_legendre\&.h>\fP
.br
\fC#include <gsl/gsl_integration\&.h>\fP
.br
\fC#include <gsl/gsl_matrix\&.h>\fP
.br
\fC#include <gsl/gsl_linalg\&.h>\fP
.br
\fC#include <gsl/gsl_blas\&.h>\fP
.br
\fC#include <gsl/gsl_monte\&.h>\fP
.br
\fC#include <gsl/gsl_monte_vegas\&.h>\fP
.br
\fC#include <gsl/gsl_odeiv2\&.h>\fP
.br
\fC#include <gsl/gsl_roots\&.h>\fP
.br
\fC#include <gsl/gsl_sf_expint\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'cuba\&.h'\fP
.br
\fC#include 'cubature\&.h'\fP
.br
\fC#include 'Global_Structs\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'cosmology\&.h'\fP
.br
\fC#include 'survey_specs\&.h'\fP
.br
\fC#include 'line_ingredients\&.h'\fP
.br
\fC#include 'wnw_split\&.h'\fP
.br
\fC#include 'IR_res\&.h'\fP
.br
\fC#include 'ps_halo_1loop\&.h'\fP
.br
\fC#include 'ps_line_pt\&.h'\fP
.br
\fC#include 'ps_line_hm\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBintegrand_parameters\fP"
.br
.RI "A structure passed to the integrators to hold the parameters fixed in the integration\&. "
.ti -1c
.RI "struct \fBintegrand_parameters2\fP"
.br
.RI "Another structure passed to the integrators to hold the parameters fixed in the integration\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_GNU_SOURCE\fP"
.br
.ti -1c
.RI "#define \fBPSC\fP   101L"
.br
.ti -1c
.RI "#define \fBST\fP   102L"
.br
.ti -1c
.RI "#define \fBTK\fP   103L"
.br
.ti -1c
.RI "#define \fBGROWTH\fP   104L"
.br
.ti -1c
.RI "#define \fBDERGROWTH\fP   105L"
.br
.ti -1c
.RI "#define \fBNONLINEAR\fP   106L"
.br
.ti -1c
.RI "#define \fBLINEAR\fP   107L"
.br
.ti -1c
.RI "#define \fBGAUSSIAN\fP   114L"
.br
.ti -1c
.RI "#define \fBNONGAUSSIAN\fP   115L"
.br
.ti -1c
.RI "#define \fBINIT\fP   116L"
.br
.ti -1c
.RI "#define \fBLOCAL\fP   117L"
.br
.ti -1c
.RI "#define \fBEQUILATERAL\fP   118L"
.br
.ti -1c
.RI "#define \fBORTHOGONAL\fP   119L"
.br
.ti -1c
.RI "#define \fBQSF\fP   120L"
.br
.ti -1c
.RI "#define \fBHS\fP   121L"
.br
.ti -1c
.RI "#define \fBNGLOOP\fP   122L"
.br
.ti -1c
.RI "#define \fBderNGLOOP\fP   123L"
.br
.ti -1c
.RI "#define \fBQUADRATIC\fP   124L"
.br
.ti -1c
.RI "#define \fBTIDE\fP   125L"
.br
.ti -1c
.RI "#define \fBGAMMA\fP   126L"
.br
.ti -1c
.RI "#define \fBLPOWER\fP   127L"
.br
.ti -1c
.RI "#define \fBNLPOWER\fP   128L"
.br
.ti -1c
.RI "#define \fBCDM\fP   90L"
.br
.ti -1c
.RI "#define \fBBA\fP   91L"
.br
.ti -1c
.RI "#define \fBTOT\fP   92L"
.br
.ti -1c
.RI "#define \fBCO10\fP   131L"
.br
.ti -1c
.RI "#define \fBCO21\fP   132L"
.br
.ti -1c
.RI "#define \fBCO32\fP   133L"
.br
.ti -1c
.RI "#define \fBCO43\fP   134L"
.br
.ti -1c
.RI "#define \fBCO54\fP   135L"
.br
.ti -1c
.RI "#define \fBCO65\fP   136L"
.br
.ti -1c
.RI "#define \fBCII\fP   137L"
.br
.ti -1c
.RI "#define \fBMATTER\fP   138L"
.br
.ti -1c
.RI "#define \fBLINEMATTER\fP   139L"
.br
.ti -1c
.RI "#define \fBLINE\fP   140L"
.br
.ti -1c
.RI "#define \fBDST\fP   141L"
.br
.ti -1c
.RI "#define \fBGFILTER\fP   142L"
.br
.ti -1c
.RI "#define \fBBSPLINE\fP   143L"
.br
.ti -1c
.RI "#define \fBTREE\fP   144L"
.br
.ti -1c
.RI "#define \fBLOOP\fP   145L"
.br
.ti -1c
.RI "#define \fBWIR\fP   146L"
.br
.ti -1c
.RI "#define \fBNOIR\fP   147L"
.br
.ti -1c
.RI "#define \fBHALO\fP   148L"
.br
.ti -1c
.RI "#define \fBPS_KMIN\fP   1\&.e\-5"
.br
.ti -1c
.RI "#define \fBPS_KMAX\fP   100\&.1"
.br
.ti -1c
.RI "#define \fBPS_ZMAX\fP   14\&."
.br
.ti -1c
.RI "#define \fBCLEANUP\fP   1"
.br
.ti -1c
.RI "#define \fBDO_NOT_EVALUATE\fP   \-1\&.0"
.br
.ti -1c
.RI "#define \fBNPARS\fP   6"
.br
.ti -1c
.RI "#define \fBMAXL\fP   2000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.RI "List of limHaloPT header files\&. "
.ti -1c
.RI "void \fBcleanup\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _GNU_SOURCE"

.SS "#define BA   91L"

.SS "#define BSPLINE   143L"

.SS "#define CDM   90L"

.SS "#define CII   137L"

.SS "#define CLEANUP   1"

.SS "#define CO10   131L"

.SS "#define CO21   132L"

.SS "#define CO32   133L"

.SS "#define CO43   134L"

.SS "#define CO54   135L"

.SS "#define CO65   136L"

.SS "#define DERGROWTH   105L"

.SS "#define derNGLOOP   123L"

.SS "#define DO_NOT_EVALUATE   \-1\&.0"

.SS "#define DST   141L"

.SS "#define EQUILATERAL   118L"

.SS "#define GAMMA   126L"

.SS "#define GAUSSIAN   114L"

.SS "#define GFILTER   142L"

.SS "#define GROWTH   104L"

.SS "#define HALO   148L"

.SS "#define HS   121L"

.SS "#define INIT   116L"

.SS "#define LINE   140L"

.SS "#define LINEAR   107L"

.SS "#define LINEMATTER   139L"

.SS "#define LOCAL   117L"

.SS "#define LOOP   145L"

.SS "#define LPOWER   127L"

.SS "#define MATTER   138L"

.SS "#define MAXL   2000"

.SS "#define NGLOOP   122L"

.SS "#define NLPOWER   128L"

.SS "#define NOIR   147L"

.SS "#define NONGAUSSIAN   115L"

.SS "#define NONLINEAR   106L"

.SS "#define NPARS   6"

.SS "#define ORTHOGONAL   119L"

.SS "#define PS_KMAX   100\&.1"

.SS "#define PS_KMIN   1\&.e\-5"

.SS "#define PS_ZMAX   14\&."

.SS "#define PSC   101L"

.SS "#define QSF   120L"

.SS "#define QUADRATIC   124L"

.SS "#define ST   102L"

.SS "#define TIDE   125L"

.SS "#define TK   103L"

.SS "#define TOT   92L"

.SS "#define TREE   144L"

.SS "#define WIR   146L"

.SH "Function Documentation"
.PP 
.SS "void cleanup ()"

.SS "void initialize ()"

.PP
List of limHaloPT header files\&. Function declarations of \fBmain\&.c\fP module
.PP
List of limHaloPT header files\&.
.PP

.br
.PP
The global structure 'gb' have several elements to hold the paths to project source directory, input, and output folders, and values of cosmological parmaeters\&.
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Change the path to the parent directory
.PP
In units of km/s
.PP
omega_b = Omega_b h^2;
.PP
3\&.0665
.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
