.TH "Line" 3 "Sat Nov 13 2021" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Line \- Structure that holds the Line-related quantities, including the interpolators for first and second moments of the line luminosity and the linear and quadratic luminosity-weighted line biases\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Global_Structs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBLineType\fP"
.br
.ti -1c
.RI "int \fBinitialized\fP"
.br
.ti -1c
.RI "size_t \fBnpointsInterp\fP"
.br
.ti -1c
.RI "double \fBline_freq\fP"
.br
.ti -1c
.RI "gsl_interp_accel * \fBmom1_accel_ptr\fP"
.br
.ti -1c
.RI "gsl_spline * \fBmom1_spline_ptr\fP"
.br
.ti -1c
.RI "gsl_interp_accel * \fBmom2_accel_ptr\fP"
.br
.ti -1c
.RI "gsl_spline * \fBmom2_spline_ptr\fP"
.br
.ti -1c
.RI "gsl_interp_accel * \fBb1_LW_accel_ptr\fP"
.br
.ti -1c
.RI "gsl_spline * \fBb1_LW_spline_ptr\fP"
.br
.ti -1c
.RI "gsl_interp_accel * \fBb2_LW_accel_ptr\fP"
.br
.ti -1c
.RI "gsl_spline * \fBb2_LW_spline_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that holds the Line-related quantities, including the interpolators for first and second moments of the line luminosity and the linear and quadratic luminosity-weighted line biases\&. 
.SH "Field Documentation"
.PP 
.SS "gsl_interp_accel* b1_LW_accel_ptr"

.SS "gsl_spline* b1_LW_spline_ptr"

.SS "gsl_interp_accel* b2_LW_accel_ptr"

.SS "gsl_spline* b2_LW_spline_ptr"

.SS "int initialized"

.SS "double line_freq"

.SS "long LineType"

.SS "gsl_interp_accel* mom1_accel_ptr"

.SS "gsl_spline* mom1_spline_ptr"

.SS "gsl_interp_accel* mom2_accel_ptr"

.SS "gsl_spline* mom2_spline_ptr"

.SS "size_t npointsInterp"


.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
