.TH "main.c" 3 "Thu Jan 20 2022" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- Documented main module, including functions to initilize and cleanup the cosmology structure and examples of calls to functions in other modules to compute the line clustering and shot power spectrum\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.RI "Initizlize the path to the required directories, set the values of cosmological parmaeters, and initialize the interpolator of the SFR(M,z) from tabulated data provided in gb\&.SFR_filename\&. "
.ti -1c
.RI "void \fBcleanup\fP (struct \fBCosmology\fP *Cx)"
.br
.RI "Free the memory allocated to cosmology structure and SFR interpolator\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBglobals\fP \fBgb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Documented main module, including functions to initilize and cleanup the cosmology structure and examples of calls to functions in other modules to compute the line clustering and shot power spectrum\&. 

Azadeh Moradinezhad Dizgah, November 4th 2021
.PP
In order to call any function from the package, the function calls should be placed in the marked section of \fBmain()\fP function\&. 
.SH "Function Documentation"
.PP 
.SS "void cleanup (struct \fBCosmology\fP * Cx)"

.PP
Free the memory allocated to cosmology structure and SFR interpolator\&. 
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "void initialize ()"

.PP
Initizlize the path to the required directories, set the values of cosmological parmaeters, and initialize the interpolator of the SFR(M,z) from tabulated data provided in gb\&.SFR_filename\&. List of limHaloPT header files\&.
.PP

.br
.PP
The global structure 'gb' have several elements to hold the paths to project source directory, input, and output folders, and values of cosmological parmaeters\&.
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Change the path to the parent directory
.PP
In units of km/s
.PP
omega_b = Omega_b h^2;
.PP
3\&.0665
.SS "int main (int argc, char * argv[])"

.SH "Variable Documentation"
.PP 
.SS "struct \fBglobals\fP gb"

.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
