.TH "ps_line_hm.c" 3 "Thu Jan 20 2022" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ps_line_hm.c \- Documented halo-model computation of line power spectrum, including clustering and stochastic contributions beyond Poisson limit\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBPS_line_HM\fP (struct \fBCosmology\fP *Cx, double k, double z, double M_min, long mode_mf, long line_type, int line_id)"
.br
.RI "Compute the clustering contribution to the line power spectrum using halo-model\&. "
.ti -1c
.RI "double \fBPS_shot_HM\fP (struct \fBCosmology\fP *Cx, double k, double z, double M_min, double *input, long mode_mf, long line_type)"
.br
.RI "Compute the shot noise contributions, including corrections beyond poisson limit (see 1706\&.08738 for more details) If nfw=1, the dependance of the power spectrum on the halo profile is neglected\&. "
.ti -1c
.RI "static int \fBmhmc_integ\fP (const int *ndim, const cubareal x[], const int *ncomp, cubareal ff[], void *p)"
.br
.RI "The integrand function passed passed to Cuhre integration routine of CUBA library to compute the corrections to mass integration\&. "
.ti -1c
.RI "void \fBmhmc\fP (struct \fBCosmology\fP *Cx, double z, long mode_mf, double *result)"
.br
.RI "Compute the corrections to mass integration of HM matter power spectrum\&. "
.ti -1c
.RI "static int \fBHM_1h2h_integ\fP (const int *ndim, const cubareal x[], const int *ncomp, cubareal ff[], void *p)"
.br
.RI "The integrand function passed passed to Cuhre integration routine to compute 1- and 2-halo integrals\&. "
.ti -1c
.RI "void \fBHM_1h2h\fP (struct \fBCosmology\fP *Cx, double k, double z, double M_min, long mode_mf, long line_type, long mode_hm, double *result)"
.br
.RI "Compute the mass integrals needed for 1- and 1-halo line, line-matter and matter power spectrum If nfw=1, the dependance of the power spectrum on the halo profile is neglected\&. "
.ti -1c
.RI "static int \fBb22_ls_integrand\fP (const int *ndim, const cubareal x[], const int *ncomp, cubareal ff[], void *p)"
.br
.RI "The integrand function passed passed to Cuhre integration routine to compute large-scale limit of b22 (shot-noise contribution) "
.ti -1c
.RI "double \fBb22_ls\fP (struct \fBCosmology\fP *Cx, double z)"
.br
.RI "Compute the large-scale limit of P_b2b2 loop\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBglobals\fP \fBgb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Documented halo-model computation of line power spectrum, including clustering and stochastic contributions beyond Poisson limit\&. 

Azadeh Moradinezhad Dizgah, November 4th 2021
.PP
This module has two main functions:
.IP "\(bu" 2
\fBPS_line_HM()\fP to compute clustering (1- and 2-halo terms)\&. The 2-halo term, includes nonlinear corrections to halo power spectrum arising from nonlinearities of matter fluctuations and halo biases\&.
.IP "\(bu" 2
\fBPS_shot_HM()\fP to compute the stochastic contrubutions beyond Poisson shot noise (see arXiv:1706\&.08738)
.PP
.PP
The other functions in these modules are utilities for computing the above two main functions\&.
.PP
In summary, the following functions can be called from other modules:
.IP "1." 4
\fBPS_line_HM()\fP computes the 1loop-HM line power spectrum
.IP "2." 4
\fBPS_shot_HM()\fP computes the full line power spectrum, beyond poisson limit
.IP "3." 4
\fBmhmc()\fP computes th corrections to mass integration of halo-model matter power spectrum
.IP "4." 4
\fBHM_1h2h()\fP performs the mass integraks for computing 1- and 2-halo terms of line-line, line-matter and matter-matter power spectra\&.
.IP "5." 4
\fBb22_ls()\fP computes the large-scale limit of P_b2b2 loop which behaves like a constant and so contributes to the shot noise\&. 
.PP

.SH "Function Documentation"
.PP 
.SS "double b22_ls (struct \fBCosmology\fP * Cx, double z)"

.PP
Compute the large-scale limit of P_b2b2 loop\&. 
.PP
\fBParameters\fP
.RS 4
\fICx\fP Input: \fBCosmology\fP structure 
.br
\fIz\fP Input: redshift 
.RE
.PP
\fBReturns\fP
.RS 4
b22_ls 
.RE
.PP

.SS "static int b22_ls_integrand (const int * ndim, const cubareal x[], const int * ncomp, cubareal ff[], void * p)\fC [static]\fP"

.PP
The integrand function passed passed to Cuhre integration routine to compute large-scale limit of b22 (shot-noise contribution) 
.PP
\fBParameters\fP
.RS 4
\fIndim\fP Input: Dimensionality of the domain of integration 
.br
\fIx\fP Input: An array of integration variables 
.br
\fIncomp\fP Input: Dimensionality of the integrand function 
.br
\fIff\fP Input: Array of values of the integrand of dimension fdim 
.br
\fIp\fP Input: integration parmaeters return the error status 
.RE
.PP

.SS "void HM_1h2h (struct \fBCosmology\fP * Cx, double k, double z, double M_min, long mode_mf, long line_type, long mode_hm, double * result)"

.PP
Compute the mass integrals needed for 1- and 1-halo line, line-matter and matter power spectrum If nfw=1, the dependance of the power spectrum on the halo profile is neglected\&. Otherwise, NFW halo profile is assumed
.PP
\fBParameters\fP
.RS 4
\fICx\fP Input: \fBCosmology\fP structure 
.br
\fIk\fP Input: wavenumber in unit of 1/Mpc\&. 
.br
\fIz\fP Input: redshift 
.br
\fIM_min\fP Input: minimum halo mass for mass integrals 
.br
\fImode_mf\fP Input: theoretical model of halo mass function to use\&. It can be set to sheth-Tormen (ST), Tinker (TR) or Press-Schecter (PSC) 
.br
\fIline_type\fP Input: name of the line to compute\&. It can be set to CII, CO10, CO21, CO32, CO43, CO54, CO65 
.br
\fImode_hm\fP Input: a switch to decide whetehr to compute gthe mass integrations\&. It can be set to:
.IP "\(bu" 2
LINE for line power spectrum,
.IP "\(bu" 2
LINEMATTER for line-matter cross spectrum
.IP "\(bu" 2
MATTER for matter power spectrum 
.PP
.br
\fIresult\fP Output: anarray of the integration results\&. Number of elements varies depending on mode_hm switch:
.IP "\(bu" 2
3 elements if mode_hm = LINE,
.IP "\(bu" 2
1 element if mode_hm = LINEMATTER
.IP "\(bu" 2
2 element if mode_hm = MATTER esults[0]: correction to 1-halo term, result[1]: correcrions to 2-halo term assuming linear halo bias 
.PP
.RE
.PP
\fBReturns\fP
.RS 4
void in unit of M_sun/Mpc^3 
.RE
.PP

.SS "static int HM_1h2h_integ (const int * ndim, const cubareal x[], const int * ncomp, cubareal ff[], void * p)\fC [static]\fP"

.PP
The integrand function passed passed to Cuhre integration routine to compute 1- and 2-halo integrals\&. 
.PP
\fBParameters\fP
.RS 4
\fIndim\fP Input: Dimensionality of the domain of integration 
.br
\fIx\fP Input: An array of integration variables 
.br
\fIncomp\fP Input: Dimensionality of the integrand function 
.br
\fIff\fP Input: Array of values of the integrand of dimension fdim 
.br
\fIp\fP Input: integration parmaeters return the error status 
.RE
.PP
we assume the profile of both matter and line are NFW
.PP
integrand of line 1halo term
.PP
integrand of 2halo term proportional to b1, the linear local-in-matter halo bias
.PP
integrand of 1halo term of line-matter cross-spectrum
.SS "void mhmc (struct \fBCosmology\fP * Cx, double z, long mode_mf, double * result)"

.PP
Compute the corrections to mass integration of HM matter power spectrum\&. 
.PP
\fBParameters\fP
.RS 4
\fICx\fP Input: \fBCosmology\fP structure 
.br
\fIz\fP Input: redshift 
.br
\fImode_mf\fP Inpute: theoretical model of halo mass function to use\&. It can be set to Press-Schecter (PSC), sheth-Tormen (ST), Tinker (TR) 
.br
\fIresult\fP Output: a 2d array of the integration results,
.IP "\(bu" 2
results[0]: correction to 1-halo term,
.IP "\(bu" 2
result[1]: correcrions to 2-halo term assuming linear halo bias 
.PP
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "static int mhmc_integ (const int * ndim, const cubareal x[], const int * ncomp, cubareal ff[], void * p)\fC [static]\fP"

.PP
The integrand function passed passed to Cuhre integration routine of CUBA library to compute the corrections to mass integration\&. When computing the matter power spectrum using halo-model, the mass integrations for 1- and 2-loop terms get contributions from halos of all masses\&. For numerical computation, we need to impose a lower and upper integration limit\&. While the result of the integration are not sensitive to the upper bound (due to the fact that the mass function drops rapidly at high M_h) the choice of the lower bound affects the results\&. We can compute the leading order corrections to the integral that are accurate up to (k R_s)^2\&. (see App\&. A of arXiv:1511\&.02231 for more details\&.)
.PP
\fBParameters\fP
.RS 4
\fIndim\fP Input: Dimensionality of the domain of integration 
.br
\fIx\fP Input: An array of integration variables 
.br
\fIncomp\fP Input: Dimensionality of the integrand function 
.br
\fIff\fP Input: Array of values of the integrand of dimension fdim 
.br
\fIp\fP Input: integration parmaeters return the error status 
.RE
.PP

.SS "double PS_line_HM (struct \fBCosmology\fP * Cx, double k, double z, double M_min, long mode_mf, long line_type, int line_id)"

.PP
Compute the clustering contribution to the line power spectrum using halo-model\&. If nfw=1, the dependance of the power spectrum on the halo profile is neglected\&. Otherwise, NFW halo profile is assumed
.PP
\fBParameters\fP
.RS 4
\fICx\fP Input: pointer to \fBCosmology\fP structure 
.br
\fIk\fP Input: wavenumber in unit of 1/Mpc\&. 
.br
\fIz\fP Input: redshift 
.br
\fIM_min\fP Input: minimum halo mass for mass integrals 
.br
\fImode_mf\fP Inpute: theoretical model of halo mass function to use\&. It can be set to sheth-Tormen (ST), Tinker (TR) or Press-Schecter (PSC) 
.br
\fIline_type\fP Inpute: name of the line to compute\&. It can be set to CII, CO10, CO21, CO32, CO43, CO54, CO65 
.br
\fIline_id\fP Inpute: id of the line to be considered\&. 
.RE
.PP
\fBReturns\fP
.RS 4
P_clust(k) 
.br
 
.RE
.PP
Boltzmann constant in unit of erg K^-1
.PP
in unit of erg/s
.PP
CII
.PP
to plot the power spectrum in units of micro K^2 Mpc^3
.PP
in unit of M_sun/Mpc^3
.SS "double PS_shot_HM (struct \fBCosmology\fP * Cx, double k, double z, double M_min, double * input, long mode_mf, long line_type)"

.PP
Compute the shot noise contributions, including corrections beyond poisson limit (see 1706\&.08738 for more details) If nfw=1, the dependance of the power spectrum on the halo profile is neglected\&. Otherwise, NFW halo profile is assumed
.PP
\fBParameters\fP
.RS 4
\fICx\fP Input: \fBCosmology\fP structure 
.br
\fIk\fP Input: wavenumber in unit of 1/Mpc\&. 
.br
\fIz\fP Input: redshift 
.br
\fIM_min\fP Input: minimum halo mass for mass integrals 
.br
\fIinput\fP inpute: an array of input values with 4 values, Tave_line, b1_line, pb22_ls, line_shot, rhom_bar 
.br
\fImode_mf\fP Inpute: theoretical model of halo mass function to use\&. It can be set to sheth-Tormen (ST), Tinker (TR) or Press-Schecter (PSC) 
.br
\fIline_type\fP Inpute: name of the line to compute\&. It can be set to CII, CO10, CO21, CO32, CO43, CO54, CO65 
.RE
.PP
\fBReturns\fP
.RS 4
P_stoch(k) 
.br
 
.RE
.PP
Boltzmann constant in unit of erg K^-1
.PP
in unit of erg/s
.PP
CII
.PP
Since the following quantities do not depend on k, I am computing them once and pass them as input to this function
.PP
to plot the power spectrum in units of micro K^2 Mpc^3
.PP
in unit of M_sun/Mpc^3
.PP
in unit of M_sun/Mpc^3
.PP
in unit of M_sun/Mpc^3
.SH "Variable Documentation"
.PP 
.SS "struct \fBglobals\fP gb"

.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
