.TH "PS_xtr" 3 "Tue Apr 5 2022" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_xtr
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Global_Structs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBinitialized\fP"
.br
.ti -1c
.RI "gsl_interp_accel * \fBz_accel_ptr\fP"
.br
.ti -1c
.RI "gsl_interp_accel * \fBlogk_accel_ptr\fP"
.br
.ti -1c
.RI "gsl_spline2d * \fBlogpkz_spline2d_ptr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int initialized"

.SS "gsl_interp_accel* logk_accel_ptr"

.SS "gsl_spline2d* logpkz_spline2d_ptr"

.SS "gsl_interp_accel* z_accel_ptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
