.TH "region" 3 "Fri Nov 5 2021" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
region
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhypercube\fP \fBh\fP"
.br
.ti -1c
.RI "unsigned \fBsplitDim\fP"
.br
.ti -1c
.RI "unsigned \fBfdim\fP"
.br
.ti -1c
.RI "\fBesterr\fP * \fBee\fP"
.br
.ti -1c
.RI "double \fBerrmax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
