.TH "rule_s" 3 "Fri Nov 5 2021" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rule_s
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBdim\fP"
.br
.ti -1c
.RI "unsigned \fBfdim\fP"
.br
.ti -1c
.RI "unsigned \fBnum_points\fP"
.br
.ti -1c
.RI "unsigned \fBnum_regions\fP"
.br
.ti -1c
.RI "double * \fBpts\fP"
.br
.ti -1c
.RI "double * \fBvals\fP"
.br
.ti -1c
.RI "evalError_func \fBevalError\fP"
.br
.ti -1c
.RI "destroy_func \fBdestroy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
