.TH "rule75genzmalik" 3 "Fri Nov 5 2021" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rule75genzmalik
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBrule\fP \fBparent\fP"
.br
.ti -1c
.RI "double * \fBwidthLambda\fP"
.br
.ti -1c
.RI "double * \fBwidthLambda2\fP"
.br
.ti -1c
.RI "double * \fBp\fP"
.br
.ti -1c
.RI "double \fBweight1\fP"
.br
.ti -1c
.RI "double \fBweight3\fP"
.br
.ti -1c
.RI "double \fBweight5\fP"
.br
.ti -1c
.RI "double \fBweightE1\fP"
.br
.ti -1c
.RI "double \fBweightE3\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
