.TH "setup_teardown.c" 3 "Thu Apr 7 2022" "Version 1.0.0" "limHaloPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setup_teardown.c \- Documented read_input module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br
\fC#include 'read_input\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP (char *argv[], struct initialize_struct *init_struct)"
.br
.RI "Initialize the path to the required directories,and the interpolator of the SFR(M,z) from tabulated data provided in gb\&.SFR_filename\&. "
.ti -1c
.RI "void \fBcleanup\fP (struct \fBCosmology\fP *Cx)"
.br
.RI "Free the memory allocated to cosmology structure and SFR interpolator\&. "
.in -1c
.SH "Detailed Description"
.PP 
Documented read_input module\&. 

Documented setup_teardown module, including the initialize and clean functions that are called first and last thing in limHaloPT package\&.
.PP
This module provides utilityy functions to read the \&.ini file
.PP
Alberto Vallinotto, April 4th 2022
.PP
Azadeh Moradinezhad Dizgah & Alberto Vallinotto, April 4th 2022 
.SH "Function Documentation"
.PP 
.SS "void cleanup (struct \fBCosmology\fP * Cx)"

.PP
Free the memory allocated to cosmology structure and SFR interpolator\&. 
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "void initialize (char * argv[], struct initialize_struct * init_struct)"

.PP
Initialize the path to the required directories,and the interpolator of the SFR(M,z) from tabulated data provided in gb\&.SFR_filename\&. 
.br
 Read in the \&.ini file and set the values of parameters\&.
.PP
The global structure 'gb' have several elements to hold the paths to project source directory, input, and output folders, and values of cosmological parmaeters\&.
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Commment out to see the names, values and numerical values of the parameters read from \&.ini file\&.
.PP
Save the values of input parmaeters to global structure or init_struct\&. The latter is returned as the output of the \fBinitialize()\fP function\&.
.PP
Cosmological parameters corresponding to initial conditions of HiddenValley (HV) simulations
.PP
3\&.0665
.SH "Author"
.PP 
Generated automatically by Doxygen for limHaloPT from the source code\&.
